#include "images.h"

const ext_img_desc_t images[36] = {
    { "wifi", &img_wifi },
    { "bat", &img_bat },
    { "recharge", &img_recharge },
    { "Brightness_1", &img_brightness_1 },
    { "Brightness_2", &img_brightness_2 },
    { "Brightness_3", &img_brightness_3 },
    { "arrows", &img_arrows },
    { "light", &img_light },
    { "douzi_1", &img_douzi_1 },
    { "100", &img_100 },
    { "back", &img_back },
    { "line", &img_line },
    { "roasted", &img_roasted },
    { "point_white", &img_point_white },
    { "piont_black", &img_piont_black },
    { "green", &img_green },
    { "parchment", &img_parchment },
    { "drycherry", &img_drycherry },
    { "setting", &img_setting },
    { "chinese", &img_chinese },
    { "english", &img_english },
    { "CN", &img_cn },
    { "En", &img_en },
    { "zerong", &img_zerong },
    { "zerong_1", &img_zerong_1 },
    { "M&D", &img_m_d },
    { "A", &img_a },
    { "zerong_2", &img_zerong_2 },
    { "A_1", &img_a_1 },
    { "M&D_1", &img_m_d_1 },
    { "warming", &img_warming },
    { "M&D_2", &img_m_d_2 },
    { "A_2", &img_a_2 },
    { "about", &img_about },
    { "bat_2", &img_bat_2 },
    { "wifi_2", &img_wifi_2 },
};
